# Generated by Django 4.2.3 on 2023-07-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbolista',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
