# Generated by Django 4.2.3 on 2023-07-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_futbolista_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='futbolista',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='futbolista',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
