# Generated by Django 4.2.3 on 2023-07-15 22:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_futbolista_descripcion_alter_futbolista_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbolista',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
