# Generated by Django 4.2.3 on 2023-07-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_futbolista_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='futbolista',
            name='autor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='futbolista',
            name='posicion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
