# Generated by Django 4.2.3 on 2023-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_futbolista_autor_futbolista_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='futbolista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_futbolista'),
        ),
    ]
