# Generated by Django 4.2.3 on 2023-07-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
